In [1]:
import pandas as pd
import numpy as np
import yaml
import lightgbm as lgb

In [2]:
data_path = "/home/kenny/data/BTCUSDT_2023_04_01.csv"

In [6]:
chunk_size = 1000000

for chunk in pd.read_csv(data_path, chunksize=chunk_size, sep="|", iterator=True):
    first_chunk = chunk
    break

In [19]:
chunk_size = 1000000

csv_reader = pd.read_csv(data_path, chunksize=chunk_size, iterator=True, sep="|")
# first_chunk = csv_reader.get_chunk()

# for i, chunk in enumerate(csv_reader):
#     # do your data transformations here
#     # create a LightGBM dataset from the transformed data
#     # train and tune your LightGBM model with Optuna
    
#     if i == 0:
#         print('Processing first chunk')
#     elif chunk.empty:
#         print('Processing last chunk')

In [22]:
import math
total_chunks = math.ceil(sum(1 for line in open(data_path)) / chunk_size)
for i, chunk in enumerate(csv_reader):
    print(i)
    if i == 0:
        print('Processing first chunk')
    elif i == total_chunks - 1:
        print('Processing last chunk')
csv_reader.seek(0)

AttributeError: 'TextFileReader' object has no attribute 'seek'

In [7]:
first_chunk.head(10)

,px_buy_1,amt_buy_1,px_buy_2,amt_buy_2,px_buy_3,amt_buy_3,px_buy_4,amt_buy_4,px_buy_5,amt_buy_5,...,amt_sell_25,aggr_trade_last_buy_px,aggr_trade_last_buy_amt,aggr_trade_last_buy_cnt,aggr_trade_last_sell_px,aggr_trade_last_sell_amt,aggr_trade_last_sell_cnt,adapter_time,host_time,sent_time
0,NaN,0.000,NaN,0.000,NaN,0.000,NaN,0.000,NaN,0.000,...,0.000,28442.5,0.051,1,0.0,0.000,0,0,0,0
1,NaN,0.000,NaN,0.000,NaN,0.000,NaN,0.000,NaN,0.000,...,0.000,28442.5,0.051,1,28442.4,0.131,3,0,0,0
2,NaN,0.000,NaN,0.000,NaN,0.000,NaN,0.000,NaN,0.000,...,0.000,28442.5,0.613,5,28442.4,0.131,3,0,0,0
3,28441.1,5.617,28441.0,2.062,28440.8,0.166,28440.7,0.001,28440.6,0.507,...,0.014,28442.5,0.613,5,28442.4,0.131,3,1680307453684608112,0,0
4,28441.1,5.617,28441.0,2.062,28440.8,0.166,28440.7,0.001,28440.6,0.507,...,0.014,28442.5,0.613,5,28442.4,2.402,12,1680307453684608112,0,0
5,28441.1,5.617,28441.0,2.062,28440.8,0.166,28440.7,0.001,28440.6,0.507,...,0.014,28442.5,0.613,5,28442.4,0.369,4,1680307453684608112,0,0
6,28441.1,5.617,28441.0,2.062,28440.8,0.166,28440.7,0.001,28440.6,0.507,...,0.014,28442.5,0.195,2,28442.4,0.369,4,1680307453684608112,0,0
7,28441.1,5.617,28441.0,2.062,28440.8,0.166,28440.7,0.001,28440.6,0.507,...,0.014,28442.5,0.195,2,28442.4,0.128,1,1680307453684608112,0,0
8,28441.1,5.617,28441.0,2.062,28440.8,0.166,28440.7,0.001,28440.6,0.507,...,0.014,28442.5,0.006,2,28442.4,0.128,1,1680307453684608112,0,0
9,28441.1,5.617,28441.0,2.062,28440.8,0.166,28440.7,0.001,28440.6,0.507,...,0.014,28442.5,0.006,2,28442.4,0.270,2,1680307453684608112,0,0

In [3]:
data = pd.read_csv(data_path, sep="|")

In [3]:
params_config = "/home/kenny/TradingExperiments/experiments_results/exp_1/model_best_params.yaml"

In [5]:
# Generate random borders
start = np.random.randint(0, len(data) - 1000000)  # select 100 rows
end = start + 1000000

In [6]:
data.iloc[start:end]

,px_buy_1,amt_buy_1,px_buy_2,amt_buy_2,px_buy_3,amt_buy_3,px_buy_4,amt_buy_4,px_buy_5,amt_buy_5,...,amt_sell_25,aggr_trade_last_buy_px,aggr_trade_last_buy_amt,aggr_trade_last_buy_cnt,aggr_trade_last_sell_px,aggr_trade_last_sell_amt,aggr_trade_last_sell_cnt,adapter_time,host_time,sent_time
552663,28570.2,4.478,28570.0,0.210,28569.9,0.001,28569.7,0.004,28569.6,0.001,...,0.180,28570.3,0.035,4.0,28570.2,0.065,1.0,1.680322e+18,1.680322e+18,1.680322e+18
552664,28570.2,4.478,28570.0,0.210,28569.9,0.001,28569.7,0.004,28569.6,0.001,...,0.180,28570.3,0.035,4.0,28570.2,0.065,1.0,1.680322e+18,1.680322e+18,1.680322e+18
552665,28570.2,4.478,28570.0,0.210,28569.9,0.001,28569.7,0.004,28569.6,0.001,...,0.180,28570.3,0.035,4.0,28570.2,0.065,1.0,1.680322e+18,1.680322e+18,1.680322e+18
552666,28570.2,4.478,28570.0,0.210,28569.9,0.001,28569.7,0.004,28569.6,0.001,...,0.284,28570.3,0.035,4.0,28570.2,0.065,1.0,1.680322e+18,1.680322e+18,1.680322e+18
552667,28570.2,4.478,28570.0,0.210,28569.9,0.001,28569.7,0.004,28569.6,0.001,...,0.284,28570.3,0.035,4.0,28570.2,0.065,1.0,1.680322e+18,1.680322e+18,1.680322e+18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1552658,28381.9,18.773,28381.8,0.493,28381.7,2.735,28381.6,0.400,28381.5,0.300,...,0.356,28382.0,0.042,2.0,28381.9,0.020,1.0,1.680353e+18,1.680353e+18,1.680353e+18
1552659,28381.9,18.773,28381.8,0.493,28381.7,2.735,28381.6,0.400,28381.5,0.300,...,0.356,28382.0,0.042,2.0,28381.9,0.020,1.0,1.680353e+18,1.680353e+18,1.680353e+18
1552660,28381.9,18.773,28381.8,0.493,28381.7,2.735,28381.6,0.400,28381.5,0.300,...,0.356,28382.0,0.275,10.0,28381.9,0.020,1.0,1.680353e+18,1.680353e+18,1.680353e+18
1552661,28381.9,18.973,28381.8,0.493,28381.7,2.735,28381.6,0.131,28381.5,0.300,...,0.356,28382.0,0.275,10.0,28381.9,0.020,1.0,1.680353e+18,1.680353e+18,1.680353e+18
1552662,28381.9,18.974,28381.8,0.493,28381.7,2.735,28381.6,0.131,28381.5,0.300,...,0.356,28382.0,0.275,10.0,28381.9,0.020,1.0,1.680353e+18,1.680353e+18,1.680353e+18

In [14]:
from datetime import datetime, timedelta
import os

In [2]:
current_day = "14.03.2023"

In [4]:
dir_path = "/home/kenny/data"

In [7]:
temp = current_day.split(".")
pair_name = "BTCUSDT"

In [8]:
cur_path = os.path.join(dir_path, pair_name+"_"+temp[-1]+"_"+temp[-2]+"_"+temp[0]+".csv")
cur_path

'/home/kenny/data/BTCUSDT_2023_03_14.csv'

In [11]:
cur_path == data_path

True

In [12]:
date_object = datetime.strptime(current_day, '%d.%m.%Y').date()

In [13]:
date_object

datetime.date(2023, 3, 14)

In [15]:
previous_date = date_object - timedelta(days=1)
previous_date

datetime.date(2023, 3, 13)

In [18]:
previous_date.year

2023

In [20]:
date_string = date_object.strftime('%d.%m.%Y')
date_string

'14.03.2023'

In [4]:
from clean import read_data, feature_creation

data = read_data(data_path)
data = feature_creation(data)

In [5]:
X_train = data.head(100000).drop(["host_time", "sent_time", "TruePrice"], axis=1)
y_train = data.head(100000)["TruePrice"]

In [8]:
from sklearn.metrics import mean_squared_error
# Load best hyperparameters from YAML file
with open(params_config, 'r') as f:
    best_params = yaml.safe_load(f)

# Train and evaluate model using best hyperparameters
model = lgb.train(best_params, lgb.Dataset(X_train, y_train), verbose_eval=False)
y_pred = model.predict(X_train)
mse = mean_squared_error(y_train, y_pred)
print('Best model trained with MSE:', mse)

/home/kenny/miniconda3/envs/algotrading/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_boost_round` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
/home/kenny/miniconda3/envs/algotrading/lib/python3.10/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "

[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006393 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 34680
[LightGBM] [Info] Number of data points in the train set: 100000, number of used features: 140
[LightGBM] [Info] Start training from score 28468.303261
Best model trained with MSE: 1204.3504707584932

In [9]:
model.params

{'bagging_fraction': 0.4883012752479061,
 'bagging_freq': 8,
 'feature_fraction': 0.1321802426035132,
 'lambda_l1': 0.0678347271226502,
 'lambda_l2': 4.070812026259327e-08,
 'learning_rate': 1.8601617261301287e-05,
 'min_child_samples': 9,
 'num_leaves': 162,
 'num_iterations': 740,
 'early_stopping_round': None}

In [ ]:
# Load trained model from JSON file
with open('model.json', 'r') as f:
    model_json = json.load(f)
lgb_model_loaded = lgb.Booster(model_file=None, model_str=json.dumps(model_json))